# This swiftlint file is being used when linting on CI

# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - identifier_name
  - function_body_length
  - opening_brace
  - trailing_comma
  - function_parameter_count
  - closure_parameter_position
  - type_name
  - cyclomatic_complexity
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count # Find all the available rules by running: `swiftlint rules`

# Alternatively, specify all rules explicitly by uncommenting this option:
# only_rules: # delete `disabled_rules` & `opt_in_rules` if using this
#   - empty_parameters
#   - vertical_whitespace

# included: # paths to include during linting. `--path` is ignored if present.
#   - telemetry
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Sources/BrevoKit/GeneratedSources
  - .build/
analyzer_rules: # Rules run by `swiftlint analyze`
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 200
# they can set both implicitly with an array
type_body_length:
  - 1000 # warning
  - 1400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200

identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - req
    - key
    - app
    - App
    - url
    - URL
    - res
    - sql
    - env
    - telemetry_api_server_version
reporter: "github-actions-logging" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
