// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "brevo-kit",
    platforms: [.macOS(.v10_15), .macCatalyst(.v13), .iOS(.v13), .tvOS(.v13), .watchOS(.v6), .visionOS(.v1)],
    products: [.library(name: "BrevoKit", targets: ["BrevoKit"])],
    dependencies: [
        .package(url: "https://github.com/apple/swift-openapi-urlsession", from: "1.1.0"),
        .package(url: "https://github.com/apple/swift-log.git", from: "1.0.0"),
        .package(url: "https://github.com/apple/swift-distributed-tracing.git", from: "1.4.1"),

        // To rebuild the autogenerated files, uncomment the line below, clean the build directory,
        // and run `swift package plugin generate-code-from-openapi --target BrevoKit`
        // .package(url: "https://github.com/apple/swift-openapi-generator", from: "1.11.1"),
    ],
    targets: [
        .target(
            name: "BrevoKit",
            dependencies: [
                .product(name: "OpenAPIURLSession", package: "swift-openapi-urlsession"),
                .product(name: "Logging", package: "swift-log"),
                .product(name: "Tracing", package: "swift-distributed-tracing")
            ],
            exclude: [
                // Files used by Swift OpenAPI generator to generate sources, but not needed for compilation
                "openapi.yaml",
                "openapi-generator-config.yaml",
            ]
        ),
        .testTarget(
            name: "brevo-kitTests",
            dependencies: ["BrevoKit"]
        ),
    ]
)
